baseurl = "https://develotters.com/"
title = "DevelOtters.com"
author = "Jonatan Ivanov"
languageCode = "en-us"
theme = "mainroad"

canonifyURLs = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
disqusShortname = "develotters"
googleAnalytics = "UA-166903607-1"

[permalinks]
  posts = "/:section/:slug/"
  pages = "/:slug/"

[sitemap]
  changefreq = "daily"
  priority = 0.5

[[menu.main]]
  name = "home"
  weight = -1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "rss"
  weight = 0
  identifier = "rss"
  url = "/index.xml"

[Author]
  name = "the author"
  bio = "I'm a Software Engineer living in Seattle and a certified dragon trainer, seriously. :)"
  avatar = "img/avatar.jpg"
