baseurl = "https://develotters.com/"
title = "DevelOtters.com"
languageCode = "en-us"
theme = "mainroad"

canonifyURLs = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true

[permalinks]
  posts = "/:section/:slug/"
  pages = "/:slug/"

[sitemap]
  changefreq = "daily"
  priority = 0.5

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  name = "home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "rss"
  weight = 6
  identifier = "rss"
  url = "/index.xml"

[services.disqus]
  shortname = "develotters"
[services.googleAnalytics]
  ID = "G-HHVCZ9S2W5"
