subtitle = "A tech blog for develotters by develotters"
description = "A tech blog for develotters by develotters"
copyright = "Jonatan Ivanov"
opengraph = true
schema = true
twitter_cards = true
readmore = true
comments = true
authorbox = true
# toc = true # Enable Table of Contents
pager = true
post_meta = ["date", "author", "categories"]
mainSections = ["post"]
dateformat = "2006-01-02"
# mathjax = true
# mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js"
# mathjaxConfig = "TeX-AMS-MML_HTMLorMML"
highlightColor = "#80151a"
# customCSS = ["css/custom.css"] # Include custom CSS files
# customJS = ["js/custom.js"] # Include custom JS files

[logo]
  image = "img/develOtter.png"

[sidebar]
  home = "right"
  list = "right"
  single = true
  widgets = ["search", "recent", "categories", "social", "taglist"]

[widgets]
  recent_num = 5
  tags_counter = false

[widgets.social]
  twitter = "jonatan_ivanov"
  github = "jonatan-ivanov"
  linkedin = "jonatan-ivanov"
