description = "A tech blog from develotters to develotters"
twitter = "https://twitter.com/jonatan_ivanov"
github = "https://github.com/jonatan-ivanov"
linkedin = "https://www.linkedin.com/in/jonatan-ivanov/"
