description = "A tech blog for develotters by develotters"
images = ["img/develOtter-1200x628.png", "img/develOtter.png"]
copyright = "Jonatan Ivanov"
opengraph = true
schema = true
twitter_cards = true
readmore = true
comments = true
authorbox = true
# toc = true # Enable Table of Contents
pager = true
post_meta = ["date", "author", "categories"]
mainSections = ["post"]
dateformat = "2006-01-02"
# mathjax = true
# mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js"
# mathjaxConfig = "TeX-AMS-MML_HTMLorMML"
customCSS = ["style.css"] # Include custom CSS files
# customJS = ["js/custom.js"] # Include custom JS files

[style.vars]
  highlightColor = "#80151a"

[logo]
  image = "img/develOtter.png"
  subtitle = "A tech blog for develotters by develotters"

[sidebar]
  home = "right"
  list = "right"
  single = true
  widgets = ["search", "recent", "categories", "social", "taglist"]

[widgets]
  recent_num = 5
  tags_counter = false

[widgets.social]
  twitter = "jonatan_ivanov"
  github = "jonatan-ivanov"
  linkedin = "jonatan-ivanov"

[[widgets.social.custom]]
  title = "Mastodon"
  url = "https://mastodon.social/@jonatan_ivanov"
  icon = "mastodon.svg"
  rel = "noopener noreferrer me"
