name: Check Markdown links

on:
  push:
    branches:
    - main
  schedule:
  # Run everyday at 9:00
  - cron: '0 9 * * *'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        base-branch: 'main'
        file-path: '*.toml' # additional to *.md
        use-verbose-mode: yes
